'use client';

import { useEffect, useMemo, useState } from 'react';
import { createSupabaseBrowserClient } from '@/lib/supabase/client';
import { AppShell } from '@/components/layout/AppShell';
import { RoleGuard } from '@/components/layout/RoleGuard';
import { Card, CardHeader } from '@/components/ui/Card';
import { SectionHeader } from '@/components/ui/SectionHeader';
import { Button } from '@/components/ui/Button';
import { Select } from '@/components/ui/Select';
import { Badge } from '@/components/ui/Badge';
import { PageSkeleton } from '@/components/ui/PageSkeleton';

const REPORT_TYPES = [
  { value: 'pdf', label: 'PDF — printable procedure summary' },
  { value: 'hl7', label: 'HL7 — hospital system integration' },
  { value: 'csv', label: 'CSV — spreadsheet export' },
  { value: 'fhir', label: 'FHIR JSON — electronic health record' },
  { value: 'audit', label: 'Audit Trail — compliance record' },
];

const typeTone: Record<string, 'slate' | 'emerald' | 'sky' | 'amber' | 'rose'> = {
  pdf: 'rose',
  hl7: 'sky',
  csv: 'emerald',
  fhir: 'amber',
  audit: 'slate',
};

function buildReportContent(type: string, procedure: any): string {
  const now = new Date().toISOString();
  if (type === 'csv') {
    const header = 'procedure_id,title,status,procedure_date,generated_at';
    const row = `${procedure?.id ?? ''},${procedure?.title ?? ''},${procedure?.status ?? ''},${procedure?.procedure_date ?? ''},${now}`;
    return `${header}\n${row}`;
  }
  if (type === 'hl7') {
    return [
      `MSH|^~\\&|ProcedureFlow||EMR||${now}||ORU^R01|${Date.now()}|P|2.5`,
      `PID|1||${procedure?.id ?? 'UNKNOWN'}`,
      `OBR|1|||${procedure?.title ?? 'PROCEDURE'}|||${procedure?.procedure_date ?? now}`,
      `OBX|1|ST|REPORT||Procedure completed. Status: ${procedure?.status ?? 'unknown'}||||||F`,
    ].join('\n');
  }
  if (type === 'fhir') {
    return JSON.stringify({
      resourceType: 'DiagnosticReport',
      id: procedure?.id ?? 'unknown',
      status: procedure?.status === 'signed' ? 'final' : 'preliminary',
      code: { text: procedure?.title ?? 'Procedure Report' },
      effectiveDateTime: procedure?.procedure_date ?? now,
      issued: now,
      conclusion: procedure?.impression ?? procedure?.findings ?? 'Report generated by ProcedureFlow',
    }, null, 2);
  }
  if (type === 'audit') {
    return JSON.stringify({
      event: 'report_generated',
      procedure_id: procedure?.id ?? 'unknown',
      procedure_title: procedure?.title ?? 'Unknown',
      procedure_status: procedure?.status ?? 'unknown',
      generated_at: now,
      platform: 'ProcedureFlow',
    }, null, 2);
  }
  // Default: PDF text
  return [
    `=== PROCEDURE REPORT ===`,
    `Generated: ${now}`,
    ``,
    `Procedure: ${procedure?.title ?? 'Untitled'}`,
    `Date: ${procedure?.procedure_date ?? '—'}`,
    `Status: ${procedure?.status ?? '—'}`,
    ``,
    `--- Clinical Notes ---`,
    procedure?.notes ?? '(none)',
    ``,
    `--- Findings ---`,
    procedure?.findings ?? '(none)',
    ``,
    `--- Impression ---`,
    procedure?.impression ?? '(none)',
    ``,
    `--- Complications ---`,
    procedure?.complications ?? '(none)',
    ``,
    `=== END REPORT ===`,
  ].join('\n');
}

export default function ReportsPage() {
  const supabase = useMemo(() => createSupabaseBrowserClient(), []);
  const [reports, setReports] = useState<any[]>([]);
  const [procedures, setProcedures] = useState<any[]>([]);
  const [selectedProcedureId, setSelectedProcedureId] = useState('');
  const [selectedType, setSelectedType] = useState('pdf');
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [status, setStatus] = useState('');

  const loadReports = async () => {
    setLoading(true);
    const [reportRes, procedureRes] = await Promise.all([
      supabase.from('reports').select('*').order('created_at', { ascending: false }),
      supabase.from('procedures').select('id,title,status,procedure_date,notes,findings,impression,complications').order('created_at', { ascending: false }),
    ]);
    setReports(reportRes.data ?? []);
    setProcedures(procedureRes.data ?? []);
    setLoading(false);
  };

  useEffect(() => {
    loadReports();
  }, []);

  const generateReport = async () => {
    const procedure = procedures.find((p) => p.id === selectedProcedureId) ?? procedures[0];
    if (!procedure) {
      setStatus('No procedure available. Create a procedure first.');
      return;
    }
    setGenerating(true);
    setStatus('');
    const content = buildReportContent(selectedType, procedure);
    const { error } = await supabase.from('reports').insert({
      procedure_id: procedure.id,
      type: selectedType,
      content,
    });
    if (error) {
      setStatus(error.message);
    } else {
      setStatus(`${selectedType.toUpperCase()} report generated for "${procedure.title}".`);
      await loadReports();
    }
    setGenerating(false);
  };

  const downloadReport = (report: any) => {
    const mimeMap: Record<string, string> = {
      pdf: 'text/plain',
      hl7: 'text/plain',
      csv: 'text/csv',
      fhir: 'application/json',
      audit: 'application/json',
    };
    const extMap: Record<string, string> = {
      pdf: 'txt', hl7: 'hl7', csv: 'csv', fhir: 'json', audit: 'json',
    };
    const mime = mimeMap[report.type] ?? 'text/plain';
    const ext = extMap[report.type] ?? 'txt';
    const blob = new Blob([report.content ?? ''], { type: `${mime};charset=utf-8` });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `procedureflow-report-${report.id.slice(0, 8)}.${ext}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const deleteReport = async (id: string) => {
    if (!confirm('Delete this report?')) return;
    await supabase.from('reports').delete().eq('id', id);
    await loadReports();
  };

  if (loading) return <AppShell><PageSkeleton /></AppShell>;

  return (
    <AppShell>
      <RoleGuard roles={['admin', 'physician']}>
        <>
          <SectionHeader
            title="Automated Report Generation"
            description="Generate structured procedure reports in multiple formats — PDF, HL7, CSV, FHIR JSON, and Audit Trail. Download reports for EMR submission, billing, or compliance purposes."
          />

          <div className="grid gap-6 lg:grid-cols-[1fr_2fr]">
            {/* Generator Card */}
            <Card>
              <CardHeader title="Generate New Report" subtitle="Select a procedure and output format." />
              <div className="space-y-4">
                <label className="block text-sm font-medium text-slate-600">
                  Procedure
                  <Select
                    className="mt-2"
                    value={selectedProcedureId}
                    onChange={(e) => setSelectedProcedureId(e.target.value)}
                  >
                    <option value="">— Select procedure —</option>
                    {procedures.map((p) => (
                      <option key={p.id} value={p.id}>
                        {p.title} · {p.procedure_date} ({p.status})
                      </option>
                    ))}
                  </Select>
                </label>
                <label className="block text-sm font-medium text-slate-600">
                  Report format
                  <Select
                    className="mt-2"
                    value={selectedType}
                    onChange={(e) => setSelectedType(e.target.value)}
                  >
                    {REPORT_TYPES.map((t) => (
                      <option key={t.value} value={t.value}>{t.label}</option>
                    ))}
                  </Select>
                </label>
                <Button onClick={generateReport} disabled={generating || procedures.length === 0}>
                  {generating ? 'Generating...' : 'Generate report'}
                </Button>
                {status ? (
                  <p className={`text-sm ${status.includes('error') || status.includes('Error') ? 'text-rose-600' : 'text-slate-500'}`}>
                    {status}
                  </p>
                ) : null}
              </div>
              <div className="mt-6 space-y-2">
                <p className="text-xs font-semibold uppercase tracking-[0.3em] text-slate-400">Format guide</p>
                {REPORT_TYPES.map((t) => (
                  <div key={t.value} className="flex items-center gap-2 text-xs text-slate-500">
                    <Badge label={t.value.toUpperCase()} tone={typeTone[t.value] ?? 'slate'} />
                    <span>{t.label.split(' — ')[1]}</span>
                  </div>
                ))}
              </div>
            </Card>

            {/* Reports List */}
            <Card>
              <CardHeader title="Generated Reports" subtitle={`${reports.length} report${reports.length !== 1 ? 's' : ''} on file`} />
              <div className="space-y-3">
                {reports.length === 0 ? (
                  <p className="text-sm text-slate-500">No reports yet. Use the form to generate your first report.</p>
                ) : (
                  reports.map((report) => {
                    const proc = procedures.find((p) => p.id === report.procedure_id);
                    const rawContent = String(report.content ?? '');
                    const created = report.created_at ? new Date(report.created_at).toLocaleString() : '—';

                    const buildSnippet = () => {
                      if (report.type === 'fhir' || report.type === 'audit') {
                        try {
                          const parsed = JSON.parse(rawContent);
                          if (report.type === 'fhir') {
                            return parsed.conclusion ?? parsed.text?.div ?? 'FHIR diagnostic report';
                          }
                          if (report.type === 'audit') {
                            return `${parsed.event ?? 'Audit event'} · ${parsed.procedure_title ?? ''}`.trim();
                          }
                        } catch {
                          return rawContent.slice(0, 140);
                        }
                      }
                      if (report.type === 'hl7') {
                        return rawContent.split('\n')[0] ?? 'HL7 message';
                      }
                      if (report.type === 'csv') {
                        const [header, row] = rawContent.split('\n');
                        return row ? row : header ?? 'CSV export';
                      }
                      if (report.type === 'pdf') {
                        // treat as structured plain text
                        const lines = rawContent.split('\n').filter(Boolean);
                        return lines.slice(0, 3).join(' ') || 'Report content';
                      }
                      // structured (JSON string) fallback
                      try {
                        const parsed = JSON.parse(rawContent);
                        if (typeof parsed === 'object') {
                          return (
                            parsed.summary ??
                            parsed.findings ??
                            parsed.impression ??
                            Object.values(parsed)[0] ??
                            'Structured report'
                          );
                        }
                      } catch {
                        /* ignore */
                      }
                      return rawContent.split('\n')[0] || 'Report content';
                    };

                    const snippet = buildSnippet();
                    return (
                      <div
                        key={report.id}
                        className="flex items-start justify-between gap-4 rounded-2xl border border-slate-200 bg-white px-4 py-3"
                      >
                        <div className="min-w-0">
                          <div className="flex items-center gap-2">
                            <Badge label={report.type?.toUpperCase() ?? 'REPORT'} tone={typeTone[report.type] ?? 'slate'} />
                            <p className="truncate text-sm font-semibold text-slate-800">
                              {proc?.title ?? report.procedure_id ?? 'Unknown procedure'}
                            </p>
                          </div>
                          <p className="mt-1 text-xs text-slate-400">{created}</p>
                          <p className="mt-1 line-clamp-2 max-w-xs text-xs text-slate-500">{snippet}</p>
                        </div>
                        <div className="flex shrink-0 flex-col gap-2">
                          <Button variant="secondary" onClick={() => downloadReport(report)}>
                            Download
                          </Button>
                          <Button variant="danger" onClick={() => deleteReport(report.id)}>
                            Delete
                          </Button>
                        </div>
                      </div>
                    );
                  })
                )}
              </div>
            </Card>
          </div>
        </>
      </RoleGuard>
    </AppShell>
  );
}
